name: Deploy Frontend

on:
  push:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build  # Este comando construye la aplicación

    - name: Clean known_hosts
      run: |
        rm -f ~/.ssh/known_hosts  # Limpiar el archivo known_hosts para evitar posibles claves incorrectas

    - name: Add SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        # Agregar la clave del servidor remoto al archivo known_hosts
        ssh-keyscan -p 5288 149.50.137.22 >> ~/.ssh/known_hosts
        # Verificar que la clave se agregó correctamente
        cat ~/.ssh/known_hosts

    - name: Deploy to server
      run: |
        scp -P 5288 -r ./dist/* root@149.50.137.22:/var/www/html
